### ISSUE TITLE
Spell checker not working

### ISSUE THREAD

**Issue by justdaj** [RainLoop/rainloop-webmail#908]
The spell checker on the browser is not working on the body of an email.  It works on the subject line, just not the main content.  I've tried it on Chrome & Firefox on the Mac.

I'm using v 1.9.3.365

Any thoughts?

thanks

**Comment by tinolin** [comment]
+1 yes. This issue is real.

**Comment by anthony-b** [comment]
+1 Same. Basic function not working.

**Comment by arcanemagick** [comment]
Spell checking works if the message is switched to plain text.  But I would also like to see this working when composing with HTML formatting.

**Comment by arcanemagick** [comment]
Turns out this is fixed in v1.9.4.398.

**Comment by anthony-b** [comment]
When did this version get released? I see that it's the lasted stable release I'm just wondering when it because available as stable.

**Comment by arcanemagick** [comment]
According to [http://www.rainloop.net/changelog/](url) the v1.9.4 release date was 05-Feb-2016.

**Comment by RainLoop** [comment]
It should working in the last stable version (released today)

**Comment by anthony-b** [comment]
@arcanemagick Ive just updated and I still dont have the spell checker. Im using Chrome. Ive also tried in plain text mode. Is there a setting that I have to turn on or anything?

**Comment by RainLoop** [comment]
Just checked http://demo.rainloop.net/ (Chrome/Windows 10):

![image](https://cloud.githubusercontent.com/assets/5530092/13574933/6642d172-e497-11e5-88e0-50670bdbb6c4.png)

**Comment by arcanemagick** [comment]
@anthony-b  I don't use Chrome, but it should have its spell checker enabled by default.  I guess you can right-click in the message body and take a look at the spell checker options to confirm that it's enabled.  Otherwise, I don't know why it wouldn't be working in the latest release.
